### ISSUE TITLE
New Mail Indicator: error, no known email client found.

### ISSUE THREAD

**Issue by maxsin** [fthx/new-mail-indicator#1]
Hi,

I'm getting 

> New Mail Indicator: error, no known email client found.

even though when running
`xdg-mime query default x-scheme-handler/mailto`
I'm getting
`org.gnome.Evolution.desktop`

Also after having the envelop icon in the tray I get 

> Execution of "undefined" failed:
Expected type filename for Argument "command_line" but got

Best regards

P.S Machine has Ubuntu 18.04

**Comment by fthx** [comment]
Hi,

Did you upgrade to version 18 (already available since few days here : https://extensions.gnome.org/extension/1505/new-mail-indicator/ ) ?
Previous version did not work with GS 3.28 (I do use GS 3.36). In Ubuntu 18.04, this one was successfully tested by me and two other error reporters.

Please confirm it's ok for you too, so I can close this issue. Thanks for reporting !

**Comment by maxsin** [comment]
I've just reinstalled it and now it works.
Thank you for the support!

**Comment by fthx** [comment]
GS 3.36 does notify on extensions updates ;-) but not 3.28...
Thanks for the feedback.
