### ISSUE TITLE
Suggestions : Options/Settings for change New Mail Indicator position in panel

### ISSUE THREAD

**Issue by Anifyuli** [fthx/new-mail-indicator#15]
Hello, Bro.
I have small suggestions for this GNOME extension. I think it more flexible if we can move it to other positions, such as in right or left position in panel. If it positioned in center, it look like have a some distances to clock, it's far. You can look in my screenshot.

This is before New Mail Indicator enabled
![image](https://github.com/fthx/new-mail-indicator/assets/73734843/4e848d44-8618-4acf-a8a1-f7221399ead8)
This is after New Mail Indicator enabled
![image](https://github.com/fthx/new-mail-indicator/assets/73734843/85fd2bfe-046b-406b-b218-609cff3d3f5d)

I mean it look better to decrease it distance from clock and have options to chnaging it position in left or right on panel. Thanks for reading my suggestions. Sorry my English. I like your GNOME extension.

System info : 
Distro : Ubuntu 23.10
GNOME version : 45

**Comment by fthx** [comment]
I did not add any padding here.
This icon is placed beside the notification area. I won't make placement options since I just maintain this extension living as this. But you can hack extension.js file here:
https://github.com/fthx/new-mail-indicator/blob/64fdee120d4664e3970093e1006051c9b59621f7/extension.js#L116
in an obvious way.
