### ISSUE TITLE
Thunderbird 78

### ISSUE THREAD

**Issue by shmu26** [fthx/new-mail-indicator#8]
I am on Ubuntu 20.04, I installed the extension and it worked flawlessly with the default Thunderbird 68 offered in the Ubuntu Repo.
Then I upgraded myself to Thunderbird 78 (which Ubuntu 20.04 LTS is soon to do anyways!) and the extension didn't work anymore.
Is this a glitch on my side, or has it not been tested with Thunderbird 78?

**Comment by fthx** [comment]
It cannot be more tested since I use Ubuntu 20.04 since its dev phase, I used TB 78 deb from Groovy then now I use TB 78 snap since 6 months.
:-)

To be sure, I just checked at TB 78 from focal-proposed and the app desktop name is still "thunderbird.desktop".
So it's on your side. I would first check if TB is the default email client in GNOME Settings. If you get TB notifications in GNOME notif area, it's 99 % on this side you have to search for.

I close this now, but tell me anyway what was your problem and how you solved it.

**Comment by fthx** [comment]
I just saw your comment in GS ext website, thanks. I find you here too, so you could be interested in the upcoming v28.
Could you confirm this version (just copy-paste the new code in extension.js) is working with TB 78 deb version? Thanks!
